/**
 * المنهج الموسّع — مواضيع تدريب إضافية تُدرَّب بالخلفية بعد اكتمال المنهج الأساسي.
 * يُستورد في aitraining.ts ويُدمج في AI_TOPICS. كل اسم `topic` هنا فريد ولا
 * يكرّر أي موضوع في المنهج الأساسي (حارس assertNoDupes يتحقق عند الاستيراد).
 *
 * التصنيف: لواو/روبلكس عميق، أنظمة روبلكس جاهزة، بايثون، جافاسكريبت/TS،
 * C++، أساسيات علوم الحاسب (لغة-محايدة)، ومهارات وأدوات المبرمج.
 */
import type { AITopic } from "./aitraining";

const PY = "بايثون";
const PY_CTX = "مفسر بايثون 3";
const JS = "جافاسكريبت";
const JS_CTX = "متصفح أو Node.js";
const TS = "TypeScript";
const TS_CTX = "Node.js مع tsc";
const CPP = "C++";
const CPP_CTX = "مترجم g++";

/* ═══════════════════════ لواو / روبلكس — تعمّق (خدمات وأنظمة المحرك) ═══════════════════════ */
const ROBLOX_DEEP: AITopic[] = [
  // ── خدمات المحرك ──
  { topic: "خدمة RunService والأطوار", kind: "lesson", level: "متوسط", focus: "Heartbeat/Stepped/RenderStepped ومتى تستخدم كلاً منها + حلقة كل إطار بأمان" },
  { topic: "UserInputService لالتقاط المدخلات", kind: "lesson", level: "متوسط", focus: "InputBegan/Ended + المفاتيح واللمس والجيمباد + التحقق من gameProcessed" },
  { topic: "ContextActionService وربط الأفعال", kind: "lesson", level: "متوسط", focus: "BindAction/UnbindAction وأزرار الموبايل التلقائية والأولويات" },
  { topic: "CollectionService والوسوم Tags", kind: "lesson", level: "متوسط", focus: "AddTag/GetTagged/GetInstanceAddedSignal لإدارة كائنات متشابهة" },
  { topic: "ProximityPrompt للتفاعل القريب", kind: "lesson", level: "مبتدئ", focus: "إعداد المحفّز + Triggered + التحقق من المسافة على السيرفر" },
  { topic: "Attributes الخصائص على الكائنات", kind: "lesson", level: "متوسط", focus: "SetAttribute/GetAttribute/GetAttributeChangedSignal كبديل نظيف للقيم" },
  { topic: "StreamingEnabled وتحميل العالم تدريجياً", kind: "lesson", level: "متقدم", focus: "كيف يؤثر على WaitForChild والكائنات البعيدة + أفضل الممارسات" },
  { topic: "Actors ولواو المتوازي", kind: "lesson", level: "متقدم", focus: "task.desynchronize/synchronize وحدود Parallel Luau والأمان" },
  { topic: "مكتبة task في لواو", kind: "lesson", level: "متوسط", focus: "task.wait/spawn/defer/delay والفرق عن wait/spawn القديمة" },
  { topic: "buffer للبيانات الثنائية في لواو", kind: "lesson", level: "متقدم", focus: "buffer.create وقراءة/كتابة الأرقام لتوفير الذاكرة والنقل" },
  { topic: "خدمة Debris لحذف الكائنات مؤقتاً", kind: "lesson", level: "مبتدئ", focus: "Debris:AddItem بدل انتظار يدوي + متى تستخدمها" },
  { topic: "خدمة SoundService والصوت المكاني", kind: "lesson", level: "متوسط", focus: "تشغيل Sound + الصوت ثلاثي الأبعاد + مجموعات الصوت" },
  { topic: "خدمة TeleportService بين الخوادم", kind: "lesson", level: "متقدم", focus: "TeleportAsync + تمرير بيانات + معالجة الفشل بأمان" },
  { topic: "خدمة MessagingService للتراسل بين الخوادم", kind: "lesson", level: "متقدم", focus: "PublishAsync/SubscribeAsync وحدودها واستخداماتها" },
  { topic: "خدمة MemoryStoreService", kind: "lesson", level: "متقدم", focus: "قوائم وخرائط سريعة عابرة للخوادم + متى تفضّلها على DataStore" },
  { topic: "خدمة HttpService وطلبات الويب الآمنة", kind: "lesson", level: "متقدم", focus: "RequestAsync + JSONEncode/Decode + الأمان وحدود المعدل" },
  { topic: "خدمة TextChatService الحديثة", kind: "lesson", level: "متوسط", focus: "الرسائل والأوامر المخصصة والقنوات في النظام الجديد" },
  { topic: "خدمة Players والانضمام والمغادرة", kind: "lesson", level: "مبتدئ", focus: "PlayerAdded/Removing + CharacterAdded والتعامل الآمن" },
  { topic: "خدمة Lighting والوقت والجو", kind: "lesson", level: "متوسط", focus: "ClockTime/Ambient/FogEnd وتغييرها برمجياً" },
  { topic: "تنظيم حاويات روبلكس الأساسية", kind: "lesson", level: "مبتدئ", focus: "ReplicatedStorage/ServerStorage/ServerScriptService وأين يوضع كل كود" },
  { topic: "حاويات البداية StarterGui وStarterPack", kind: "lesson", level: "مبتدئ", focus: "كيف تُنسخ للاعب عند الظهور + StarterPlayerScripts" },
  { topic: "خدمة PhysicsService ومجموعات التصادم", kind: "lesson", level: "متقدم", focus: "CollisionGroups لمنع تصادم مجموعات معينة" },
  { topic: "خدمة LocalizationService والترجمة", kind: "lesson", level: "متقدم", focus: "جداول الترجمة ودعم لغات متعددة في اللعبة" },
  { topic: "خدمة BadgeService ومنح الشارات", kind: "lesson", level: "متوسط", focus: "AwardBadge + التحقق من الامتلاك بأمان" },
  { topic: "خدمة MarketplaceService ومنتجات المطور", kind: "lesson", level: "متقدم", focus: "PromptProductPurchase + ProcessReceipt الآمن ومنع الاحتيال" },
  { topic: "gamepass والتحقق من الامتلاك", kind: "lesson", level: "متوسط", focus: "UserOwnsGamePassAsync + منح المزايا مرة واحدة" },
  { topic: "Developer Products والشراء المتكرر", kind: "lesson", level: "متقدم", focus: "منتجات قابلة للشراء عدة مرات + سجل الإيصالات لمنع التكرار" },
  { topic: "خدمة InsertService وتحميل الأصول", kind: "lesson", level: "متوسط", focus: "LoadAsset + متى يُسمح بها والأمان" },

  // ── الرياضيات والفضاء ──
  { topic: "Vector3 والعمليات المتجهية", kind: "lesson", level: "متوسط", focus: "الجمع/الطرح/الضرب + Magnitude/Unit/Dot/Cross بأمثلة حركة" },
  { topic: "Vector2 والإحداثيات ثنائية البعد", kind: "lesson", level: "مبتدئ", focus: "استخداماتها في الواجهات والشاشة" },
  { topic: "CFrame والتحويلات المكانية", kind: "lesson", level: "متقدم", focus: "الموضع + الدوران + الضرب لتركيب التحويلات" },
  { topic: "تحويل الإحداثيات ToWorldSpace وToObjectSpace", kind: "lesson", level: "متقدم", focus: "التحويل بين فضاء العالم وفضاء الكائن بأمثلة" },
  { topic: "CFrame.lookAt وتوجيه الكائنات", kind: "lesson", level: "متوسط", focus: "توجيه كائن نحو هدف + كاميرا تتبع" },
  { topic: "الدوران بزوايا Euler وCFrame.Angles", kind: "lesson", level: "متوسط", focus: "بناء دوران من زوايا + rad/deg" },
  { topic: "Region3 والمناطق المكانية", kind: "lesson", level: "متقدم", focus: "تحديد منطقة + كشف الأجزاء داخلها" },
  { topic: "مكتبة math في لواو", kind: "lesson", level: "مبتدئ", focus: "floor/ceil/abs/clamp/min/max بأمثلة ألعاب" },
  { topic: "math.random والبذور العشوائية", kind: "lesson", level: "مبتدئ", focus: "Random.new مقابل math.random + توزيع عادل" },
  { topic: "math.noise وضجيج بيرلن للتضاريس", kind: "lesson", level: "متقدم", focus: "توليد تضاريس/أنماط ناعمة عبر الضجيج" },
  { topic: "الاستيفاء الخطي lerp في الحركة", kind: "lesson", level: "متوسط", focus: "Vector3:Lerp وCFrame:Lerp لحركة ناعمة يدوية" },
  { topic: "UDim وUDim2 لأحجام الواجهات", kind: "lesson", level: "مبتدئ", focus: "Scale مقابل Offset وتصميم متجاوب" },
  { topic: "الألوان Color3 وBrickColor", kind: "lesson", level: "مبتدئ", focus: "fromRGB/fromHSV والتحويل والتدرجات" },

  // ── الكائنات والبناء ──
  { topic: "Instance.new وبناء الكائنات برمجياً", kind: "lesson", level: "مبتدئ", focus: "إنشاء + ضبط الخصائص + Parent الصحيح أخيراً" },
  { topic: "FindFirstChild وWaitForChild بأمان", kind: "lesson", level: "مبتدئ", focus: "الفرق بينهما + timeout + تجنب الأخطاء الصامتة" },
  { topic: "GetChildren وGetDescendants والمرور", kind: "lesson", level: "مبتدئ", focus: "المرور على الكائنات + IsA للتصفية" },
  { topic: "خصائص Part الأساسية", kind: "lesson", level: "مبتدئ", focus: "Anchored/CanCollide/Material/Transparency وتأثيرها" },
  { topic: "Model وPrimaryPart وPivotTo", kind: "lesson", level: "متوسط", focus: "تحريك نموذج كامل + PivotTo الحديثة" },
  { topic: "Attachment وربط النقاط", kind: "lesson", level: "متوسط", focus: "نقاط ربط للتأثيرات والقيود والقوى" },
  { topic: "WeldConstraint وMotor6D", kind: "lesson", level: "متقدم", focus: "لصق الأجزاء + المفاصل المتحركة للشخصيات" },
  { topic: "القيود الفيزيائية Constraints", kind: "lesson", level: "متقدم", focus: "SpringConstraint/RopeConstraint/HingeConstraint بأمثلة" },
  { topic: "تشكيل التضاريس Terrain برمجياً", kind: "lesson", level: "متقدم", focus: "FillBlock/FillBall والمواد وتوليد عالم" },
  { topic: "ParticleEmitter وتأثيرات الجسيمات", kind: "lesson", level: "متوسط", focus: "إعداد الانبعاث + Emit للانفجارات" },
  { topic: "Beam وTrail للتأثيرات البصرية", kind: "lesson", level: "متوسط", focus: "أشعة بين نقطتين + أثر خلف كائن متحرك" },
  { topic: "الإضاءة الموضعية PointLight وSpotLight", kind: "lesson", level: "مبتدئ", focus: "إضافة مصادر ضوء متحركة وملونة" },
  { topic: "Decal وTexture وSurfaceGui", kind: "lesson", level: "متوسط", focus: "صور على الأسطح + واجهات على الأجزاء" },

  // ── الشخصية والهيومانويد ──
  { topic: "Humanoid وحالاته HumanoidStateType", kind: "lesson", level: "متوسط", focus: "الحالات (Running/Jumping/Dead) والتحكم بها" },
  { topic: "تحريك الشخصية Humanoid:MoveTo", kind: "lesson", level: "متوسط", focus: "MoveTo/WalkToPoint + MoveToFinished" },
  { topic: "Animator وتشغيل الأنيميشن", kind: "lesson", level: "متوسط", focus: "LoadAnimation + AnimationTrack:Play على السيرفر" },
  { topic: "التحكم بمسارات الأنيميشن", kind: "lesson", level: "متقدم", focus: "الأولويات + الوزن + التوقف الناعم" },
  { topic: "بناء الأدوات Tool في روبلكس", kind: "lesson", level: "متوسط", focus: "Activated/Equipped + Handle + السيرفر مقابل الكلينت" },
  { topic: "الحقيبة Backpack وتجهيز الأدوات", kind: "lesson", level: "مبتدئ", focus: "إعطاء أدوات + StarterGear + التجهيز التلقائي" },
  { topic: "أجزاء الجسم R15 وR6", kind: "lesson", level: "متوسط", focus: "الفروق + الوصول للأجزاء + التوافق" },
  { topic: "الصحة والضرر والشفاء", kind: "lesson", level: "متوسط", focus: "Humanoid.Health/MaxHealth + TakeDamage + التجديد" },
  { topic: "ForceField والحماية المؤقتة", kind: "lesson", level: "مبتدئ", focus: "حماية اللاعب عند الظهور + إزالتها بعد مدة" },
  { topic: "المقاعد Seat وVehicleSeat", kind: "lesson", level: "متوسط", focus: "الجلوس + Occupant + التحكم بالمركبة" },

  // ── الواجهات المتقدمة ──
  { topic: "أساسيات ScreenGui وFrame", kind: "lesson", level: "مبتدئ", focus: "بنية الواجهة + الطبقات + ResetOnSpawn" },
  { topic: "عناصر النص TextLabel وTextButton", kind: "lesson", level: "مبتدئ", focus: "النص + TextScaled + RichText" },
  { topic: "الصور ImageLabel وImageButton", kind: "lesson", level: "مبتدئ", focus: "Image + ScaleType + الأيقونات" },
  { topic: "ترتيب العناصر UIListLayout", kind: "lesson", level: "متوسط", focus: "ترتيب تلقائي عمودي/أفقي + الحشو والترتيب" },
  { topic: "الشبكات UIGridLayout", kind: "lesson", level: "متوسط", focus: "جرد شبكي + CellSize متجاوب" },
  { topic: "تجميل الواجهة UICorner وUIStroke", kind: "lesson", level: "مبتدئ", focus: "زوايا دائرية + حدود + UIGradient" },
  { topic: "قيود حجم الواجهة UIAspectRatioConstraint", kind: "lesson", level: "متوسط", focus: "الحفاظ على النسب عبر الشاشات" },
  { topic: "AnchorPoint والموضع في الواجهات", kind: "lesson", level: "متوسط", focus: "التمركز الصحيح + Scale مقابل Offset" },
  { topic: "القوائم الطويلة ScrollingFrame", kind: "lesson", level: "متوسط", focus: "CanvasSize + AutomaticCanvasSize + التمرير" },
  { topic: "السحب والإفلات DragDetectors", kind: "lesson", level: "متقدم", focus: "سحب الكائنات في العالم بأمان" },
  { topic: "الواجهات المتجاوبة مع الشاشات", kind: "lesson", level: "متقدم", focus: "دعم الموبايل والحاسوب + AbsoluteSize" },
  { topic: "عرض النماذج ViewportFrame", kind: "lesson", level: "متقدم", focus: "عرض نموذج ثلاثي داخل الواجهة (معاينة عناصر)" },

  // ── الكاميرا والتأثيرات ──
  { topic: "الكاميرا Camera وCameraType", kind: "lesson", level: "متوسط", focus: "Scriptable + CFrame + FieldOfView" },
  { topic: "الكاميرا بمنظور الشخص الأول", kind: "lesson", level: "متقدم", focus: "إخفاء الجسم + ربط الكاميرا بالرأس" },
  { topic: "اهتزاز الكاميرا Camera shake", kind: "lesson", level: "متقدم", focus: "تأثير ارتجاج عند الانفجارات + العودة الناعمة" },
  { topic: "تأثيرات ما بعد المعالجة", kind: "lesson", level: "متوسط", focus: "Bloom/Blur/ColorCorrection وتغييرها ديناميكياً" },
  { topic: "دورة ليل ونهار عبر ClockTime", kind: "lesson", level: "متوسط", focus: "تحريك الوقت بسلاسة + تغيير الجو" },

  // ── البيانات والشبكة المتقدمة ──
  { topic: "UpdateAsync الآمن في DataStore", kind: "lesson", level: "متقدم", focus: "لماذا UpdateAsync أأمن من SetAsync + مثال كامل" },
  { topic: "OrderedDataStore وقوائم الصدارة العالمية", kind: "lesson", level: "متقدم", focus: "GetSortedAsync لأعلى اللاعبين عالمياً" },
  { topic: "قفل الجلسة session locking للبيانات", kind: "lesson", level: "متقدم", focus: "منع تلف البيانات عند خوادم متعددة" },
  { topic: "حدود معدل DataStore وإعادة المحاولة", kind: "lesson", level: "متقدم", focus: "احترام الحدود + backoff عند الفشل" },
  { topic: "حفظ الجداول المعقدة في DataStore", kind: "lesson", level: "متقدم", focus: "تسلسل جداول متداخلة + الإصدارات" },
  { topic: "RemoteFunction وInvokeServer الآمن", kind: "lesson", level: "متقدم", focus: "طلب/رد + مخاطر التعليق + التحقق" },
  { topic: "الفرق بين RemoteEvent وRemoteFunction", kind: "lesson", level: "متوسط", focus: "متى تستخدم كلاً منهما + النمط الصحيح" },
  { topic: "UnreliableRemoteEvent للبيانات السريعة", kind: "lesson", level: "متقدم", focus: "متى تقبل فقدان الحزم (مواضع/تأثيرات)" },
  { topic: "النسخ المتماثل replication وحدوده", kind: "lesson", level: "متقدم", focus: "ما يُنسخ تلقائياً + الفرق سيرفر/كلينت" },

  // ── مكافحة الاستغلال والأداء ──
  { topic: "مبدأ عدم الثقة بالكلينت", kind: "lesson", level: "متوسط", focus: "لماذا كل قرار مهم على السيرفر + أمثلة ثغرات" },
  { topic: "كشف الغش من جهة السيرفر", kind: "lesson", level: "متقدم", focus: "فحوص المعقولية للسرعة والموضع والمعدل" },
  { topic: "فحوص المدخلات sanity checks", kind: "lesson", level: "متوسط", focus: "التحقق من النوع والمدى والملكية قبل التنفيذ" },
  { topic: "تقييد معدل الطلبات rate limiting", kind: "lesson", level: "متقدم", focus: "منع إغراق RemoteEvent بالطلبات" },
  { topic: "تحسين الأداء وتقليل عمل كل إطار", kind: "lesson", level: "متقدم", focus: "تجنب الحسابات الثقيلة داخل Heartbeat" },
  { topic: "إدارة الاتصالات Connections وDisconnect", kind: "lesson", level: "متوسط", focus: "تخزين الاتصالات وفصلها لتجنب التسريب" },
  { topic: "تجنب تسرب الذاكرة memory leaks", kind: "lesson", level: "متقدم", focus: "مراجع معلقة + جداول تكبر بلا تنظيف" },
  { topic: "قياس الأداء بالـ microprofiler", kind: "lesson", level: "متقدم", focus: "debug.profilebegin + قراءة النتائج" },
  { topic: "تجميع الكائنات object pooling", kind: "lesson", level: "متقدم", focus: "إعادة استخدام الأجزاء بدل الإنشاء/الحذف المتكرر" },
  { topic: "التحميل المسبق PreloadAsync", kind: "lesson", level: "متوسط", focus: "تحميل الأصول قبل الحاجة لتفادي التقطيع" },
];

/* ═══════════════════════ أنظمة روبلكس جاهزة ═══════════════════════ */
const ROBLOX_SYSTEMS: AITopic[] = [
  { topic: "نظام مولد مسارات عقبات Obby", kind: "system", level: "متوسط", focus: "توليد قطع + مراحل + مخاطر متحركة" },
  { topic: "نظام نقاط تفتيش Checkpoints", kind: "system", level: "مبتدئ", focus: "حفظ آخر نقطة + إحياء اللاعب عندها" },
  { topic: "نظام تايكون Tycoon كامل", kind: "system", level: "متقدم", focus: "أزرار شراء + توليد دخل + حفظ التقدم" },
  { topic: "نظام محاكي Simulator وحلقة التطوير", kind: "system", level: "متوسط", focus: "جمع + بيع + ترقية + تكرار ممتع" },
  { topic: "نظام حيوانات أليفة Pets", kind: "system", level: "متقدم", focus: "متابعة اللاعب + مكافآت + ندرة وحفظ" },
  { topic: "نظام إعادة ميلاد Rebirth", kind: "system", level: "متوسط", focus: "تصفير التقدم مقابل مضاعِف دائم" },
  { topic: "نظام صناديق عشوائية عادلة Gacha", kind: "system", level: "متقدم", focus: "أوزان احتمالية شفافة + منع التلاعب" },
  { topic: "نظام تداول آمن بين اللاعبين", kind: "system", level: "متقدم", focus: "تأكيد مزدوج + تحقق سيرفري صارم" },
  { topic: "نظام أوامر إدارية Admin commands", kind: "system", level: "متقدم", focus: "قائمة مصرّح لهم + أوامر آمنة + تسجيل" },
  { topic: "نظام حظر اللاعبين Ban", kind: "system", level: "متقدم", focus: "حظر مؤقت/دائم عبر DataStore + رسالة طرد" },
  { topic: "نظام قوائم صدارة عالمية", kind: "system", level: "متقدم", focus: "OrderedDataStore + لوحة عرض محدّثة" },
  { topic: "نظام مهام يومية Quests", kind: "system", level: "متوسط", focus: "أهداف + تتبع تقدم + مكافآت + إعادة ضبط" },
  { topic: "نظام تصنيع Crafting", kind: "system", level: "متقدم", focus: "وصفات + مكونات + تحقق مخزون + إنتاج" },
  { topic: "نظام بناء ووضع كائنات Placement", kind: "system", level: "متقدم", focus: "معاينة + شبكة + تحقق موقع + حفظ" },
  { topic: "نظام مركبات Vehicles", kind: "system", level: "متقدم", focus: "VehicleSeat + تحكم + سرعة + أمان" },
  { topic: "نظام قتال ملحمي Combat", kind: "system", level: "متقدم", focus: "ضربات + برودة + تحقق سيرفري للضرر" },
  { topic: "تعويض التأخير في القتال lag compensation", kind: "system", level: "متقدم", focus: "التوفيق بين إحساس الكلينت وسلطة السيرفر" },
  { topic: "نظام حوار NPC Dialogue", kind: "system", level: "متوسط", focus: "شجرة خيارات + ردود + منح مهام" },
  { topic: "نظام تذكرة المعارك Battle Pass", kind: "system", level: "متقدم", focus: "مستويات موسمية + مكافآت مجانية/مدفوعة" },
  { topic: "نظام متجر بعملة مميزة", kind: "system", level: "متوسط", focus: "عملة صعبة + عناصر حصرية + شراء آمن" },
  { topic: "نظام صناديق غنائم Loot boxes", kind: "system", level: "متوسط", focus: "فتح + مؤثرات + توزيع عادل" },
  { topic: "نظام ترقيات Upgrades", kind: "system", level: "متوسط", focus: "مستويات + تكلفة متصاعدة + حفظ" },
  { topic: "نظام مستويات وخبرة XP", kind: "system", level: "متوسط", focus: "منحنى خبرة + ترقية + مكافأة مستوى" },
  { topic: "نظام إنجازات Achievements", kind: "system", level: "متوسط", focus: "شروط + منح شارة + إشعار" },
  { topic: "نظام فرق Teams", kind: "system", level: "مبتدئ", focus: "توزيع + ألوان + مناطق فريق" },
  { topic: "نظام مناطق آمنة Safe zones", kind: "system", level: "مبتدئ", focus: "منع الضرر داخل منطقة محددة" },
  { topic: "نظام طقس ديناميكي", kind: "system", level: "متوسط", focus: "مطر/ضباب متغير + تأثير بصري" },
  { topic: "نظام جولات Round system", kind: "system", level: "متوسط", focus: "مؤقت + اختيار خريطة + فائز + إعادة" },
  { topic: "نظام لوبي ومطابقة Matchmaking", kind: "system", level: "متقدم", focus: "انتظار لاعبين + بدء جولة + توزيع" },
  { topic: "نظام إشعارات داخل اللعبة", kind: "system", level: "مبتدئ", focus: "رسائل منبثقة مؤقتة + طابور" },
  { topic: "نظام شريط صحة Health bar", kind: "system", level: "مبتدئ", focus: "شريط فوق الرأس يتحدث مع الصحة" },
  { topic: "نظام سلاح ناري بالارتداد Recoil", kind: "system", level: "متقدم", focus: "إطلاق + ارتداد + انتشار + تحقق سيرفري" },
  { topic: "نظام ذخيرة وإعادة تلقيم Reload", kind: "system", level: "متوسط", focus: "عدّاد طلقات + مؤقت تلقيم + واجهة" },
  { topic: "نظام سيوف ومعارك قريبة Melee", kind: "system", level: "متوسط", focus: "منطقة إصابة + برودة + رد فعل" },
  { topic: "نظام دروع وحماية Armor", kind: "system", level: "متوسط", focus: "تقليل الضرر + طبقات + استهلاك" },
  { topic: "نظام تأثيرات حالة Status effects", kind: "system", level: "متقدم", focus: "سم/بطء/حرق مؤقت + تراكم" },
  { topic: "نظام تبريد المهارات Cooldowns", kind: "system", level: "متوسط", focus: "منع تكرار المهارة + مؤشر واجهة" },
  { topic: "نظام موارد وجمع Resources", kind: "system", level: "متوسط", focus: "عقد موارد + جمع + تجديد" },
  { topic: "نظام زراعة متقدم بمحاصيل متعددة", kind: "system", level: "متقدم", focus: "أنواع بذور + أوقات نمو + سوق بيع" },
  { topic: "نظام طبخ ووصفات Cooking", kind: "system", level: "متوسط", focus: "دمج مكونات + وصفات + جودة ناتج" },
  { topic: "نظام صيد كنوز Treasure hunt", kind: "system", level: "متوسط", focus: "خريطة + تلميحات + مكافأة اكتشاف" },
  { topic: "نظام سباق وتوقيت Races", kind: "system", level: "متوسط", focus: "بوابات + مؤقت لفة + ترتيب" },
  { topic: "نظام منصات لغز Puzzle platforms", kind: "system", level: "متوسط", focus: "مفاتيح + أبواب + تسلسل حل" },
  { topic: "نظام بوابات انتقال Teleport pads", kind: "system", level: "مبتدئ", focus: "نقل داخل الخريطة + تأثير" },
  { topic: "نظام أبواب برموز Keypad", kind: "system", level: "متوسط", focus: "لوحة أرقام + رمز صحيح + فتح" },
  { topic: "نظام مصعد وطوابق Elevator", kind: "system", level: "متوسط", focus: "أزرار طوابق + حركة ناعمة + أبواب" },
  { topic: "نظام حفظ عالم كامل Serialization", kind: "system", level: "متقدم", focus: "تحويل بناء اللاعب لبيانات وحفظه واستعادته" },
  { topic: "نظام دردشة بأوامر مخصصة", kind: "system", level: "متوسط", focus: "التقاط رسائل تبدأ بـ / وتنفيذ أفعال" },
  { topic: "نظام غرف خاصة Reserved servers", kind: "system", level: "متقدم", focus: "ReserveServer + دعوة أصدقاء لخادم خاص" },
  { topic: "نظام يوم/ليلة يؤثر على اللعب", kind: "system", level: "متوسط", focus: "أعداء ليلاً + مكافآت نهاراً" },
];

/* ═══════════════════════ بايثون — تعمّق ومشاريع ═══════════════════════ */
const PYTHON_EXT: AITopic[] = [
  { topic: "الفهم comprehensions في بايثون", kind: "lesson", level: "متوسط", focus: "list/dict/set comprehensions + شرط + تداخل", lang: PY, context: PY_CTX },
  { topic: "المزخرفات decorators في بايثون", kind: "lesson", level: "متقدم", focus: "دالة تغلّف دالة + @wraps + أمثلة توقيت/تحقق", lang: PY, context: PY_CTX },
  { topic: "مديرو السياق context managers", kind: "lesson", level: "متوسط", focus: "with + __enter__/__exit__ + contextlib", lang: PY, context: PY_CTX },
  { topic: "dataclasses في بايثون", kind: "lesson", level: "متوسط", focus: "@dataclass + الحقول والقيم الافتراضية والمقارنة", lang: PY, context: PY_CTX },
  { topic: "التلميحات النوعية typing", kind: "lesson", level: "متوسط", focus: "أنواع الدوال + Optional/List/Dict + فائدتها", lang: PY, context: PY_CTX },
  { topic: "البرمجة غير المتزامنة asyncio", kind: "lesson", level: "متقدم", focus: "async/await + gather + متى تفيد", lang: PY, context: PY_CTX },
  { topic: "اختبارات pytest", kind: "lesson", level: "متوسط", focus: "كتابة اختبارات + assert + fixtures", lang: PY, context: PY_CTX },
  { topic: "التسجيل logging في بايثون", kind: "lesson", level: "متوسط", focus: "مستويات + معالجات + بديل print", lang: PY, context: PY_CTX },
  { topic: "تحليل الوسائط argparse", kind: "lesson", level: "متوسط", focus: "بناء أداة سطر أوامر بخيارات", lang: PY, context: PY_CTX },
  { topic: "قاعدة بيانات sqlite3", kind: "lesson", level: "متوسط", focus: "اتصال + استعلامات + parametrized + حفظ", lang: PY, context: PY_CTX },
  { topic: "مكتبة requests للطلبات", kind: "lesson", level: "متوسط", focus: "GET/POST + رؤوس + JSON + أخطاء", lang: PY, context: PY_CTX },
  { topic: "أساسيات pandas للبيانات", kind: "lesson", level: "متقدم", focus: "DataFrame + قراءة CSV + تصفية وتجميع", lang: PY, context: PY_CTX },
  { topic: "أساسيات numpy والمصفوفات", kind: "lesson", level: "متقدم", focus: "ndarray + عمليات متجهية + الأداء", lang: PY, context: PY_CTX },
  { topic: "المكررات iterators بعمق", kind: "lesson", level: "متوسط", focus: "__iter__/__next__ + بناء مكرر مخصص", lang: PY, context: PY_CTX },
  { topic: "lambda والدوال العليا", kind: "lesson", level: "متوسط", focus: "map/filter/reduce + sorted بمفتاح", lang: PY, context: PY_CTX },
  { topic: "الثوابت enum في بايثون", kind: "lesson", level: "متوسط", focus: "Enum + قيم مسماة نظيفة", lang: PY, context: PY_CTX },
  { topic: "الوراثة المتعددة وترتيب MRO", kind: "lesson", level: "متقدم", focus: "super() + ترتيب الحل + المزج mixins", lang: PY, context: PY_CTX },
  { topic: "الخصائص property في الأصناف", kind: "lesson", level: "متوسط", focus: "@property + getters/setters محسوبة", lang: PY, context: PY_CTX },
  { topic: "args وkwargs بعمق", kind: "lesson", level: "متوسط", focus: "تمرير مرن + فك التغليف * و**", lang: PY, context: PY_CTX },
  { topic: "التعامل مع JSON وCSV في بايثون", kind: "lesson", level: "مبتدئ", focus: "json وcsv للقراءة والكتابة", lang: PY, context: PY_CTX },
  { topic: "البيئات الافتراضية venv وpip", kind: "lesson", level: "مبتدئ", focus: "عزل الحزم + requirements.txt", lang: PY, context: "طرفية النظام مع بايثون 3" },
  { topic: "مكتبة collections في بايثون", kind: "lesson", level: "متوسط", focus: "deque/Counter/defaultdict بأمثلة", lang: PY, context: PY_CTX },
  { topic: "مكتبة itertools", kind: "lesson", level: "متقدم", focus: "chain/combinations/groupby عملية", lang: PY, context: PY_CTX },
  { topic: "مكتبة functools", kind: "lesson", level: "متقدم", focus: "lru_cache + partial + reduce", lang: PY, context: PY_CTX },
  { topic: "الاستثناءات المخصصة في بايثون", kind: "lesson", level: "متوسط", focus: "توريث Exception + رفع ومعالجة", lang: PY, context: PY_CTX },
  { topic: "مشروع كاشط ويب بايثون", kind: "system", level: "متقدم", focus: "requests + تحليل HTML + حفظ نتائج", lang: PY, context: PY_CTX },
  { topic: "مشروع واجهة برمجية Flask", kind: "system", level: "متقدم", focus: "مسارات + JSON + تشغيل خادم بسيط", lang: PY, context: "بايثون 3 مع Flask" },
  { topic: "مشروع بوت ديسكورد بايثون", kind: "system", level: "متقدم", focus: "أوامر + أحداث + رد تلقائي", lang: PY, context: "بايثون 3 مع discord.py" },
  { topic: "مشروع معالجة ملفات Excel", kind: "system", level: "متوسط", focus: "openpyxl قراءة/كتابة + تلخيص", lang: PY, context: "بايثون 3 مع openpyxl" },
  { topic: "مشروع أتمتة تنظيم صور", kind: "system", level: "متوسط", focus: "فرز حسب التاريخ/النوع + نقل", lang: PY, context: PY_CTX },
  { topic: "مشروع لعبة نص تفاعلية", kind: "system", level: "متوسط", focus: "قصة بخيارات + حالة + نهايات", lang: PY, context: PY_CTX },
  { topic: "مشروع مولد كلمات مرور قوية", kind: "system", level: "مبتدئ", focus: "عشوائية + طول + رموز + نسخ", lang: PY, context: PY_CTX },
  { topic: "الأنماط regex المتقدمة في بايثون", kind: "lesson", level: "متقدم", focus: "مجموعات + lookahead + استبدال", lang: PY, context: PY_CTX },
  { topic: "التعبيرات المولّدة generator expressions", kind: "lesson", level: "متوسط", focus: "كسل + توفير ذاكرة مقابل القوائم", lang: PY, context: PY_CTX },
  { topic: "التواريخ والمناطق الزمنية في بايثون", kind: "lesson", level: "متوسط", focus: "datetime + timedelta + zoneinfo", lang: PY, context: PY_CTX },
  { topic: "مشروع تطبيق سطر أوامر كامل", kind: "system", level: "متقدم", focus: "argparse + وحدات + حفظ إعداد", lang: PY, context: "بايثون 3 (طرفية)" },
  { topic: "مشروع تحليل بيانات CSV بسيط", kind: "system", level: "متوسط", focus: "قراءة + إحصاءات + أعلى/أدنى", lang: PY, context: PY_CTX },
  { topic: "مشروع خادم ويب بلا إطار", kind: "system", level: "متقدم", focus: "http.server + مسارات بسيطة", lang: PY, context: PY_CTX },
  { topic: "المزامنة threading مقابل multiprocessing", kind: "lesson", level: "متقدم", focus: "الفرق + GIL + متى كلٌّ منهما", lang: PY, context: PY_CTX },
  { topic: "التغليف والخصوصية في أصناف بايثون", kind: "lesson", level: "متوسط", focus: "_ و__ + الأسماء المشوّهة", lang: PY, context: PY_CTX },
];

/* ═══════════════════════ جافاسكريبت / TypeScript — تعمّق ومشاريع ═══════════════════════ */
const JS_EXT: AITopic[] = [
  { topic: "الإغلاقات closures في جافاسكريبت", kind: "lesson", level: "متوسط", focus: "التقاط النطاق + عدّاد خاص + مزالق", lang: JS, context: JS_CTX },
  { topic: "النماذج الأولية prototypes والوراثة", kind: "lesson", level: "متقدم", focus: "سلسلة البروتوتايب + __proto__ + Object.create", lang: JS, context: JS_CTX },
  { topic: "حلقة الأحداث event loop", kind: "lesson", level: "متقدم", focus: "المكدس + الطابور + microtasks + الترتيب", lang: JS, context: JS_CTX },
  { topic: "الوحدات modules في جافاسكريبت", kind: "lesson", level: "متوسط", focus: "import/export + default + إعادة تصدير", lang: JS, context: JS_CTX },
  { topic: "الوعود Promise بعمق", kind: "lesson", level: "متوسط", focus: "then/catch/finally + التسلسل + الأخطاء", lang: JS, context: JS_CTX },
  { topic: "async/await ومعالجة الأخطاء", kind: "lesson", level: "متوسط", focus: "try/catch حول await + تجنب المزالق", lang: JS, context: JS_CTX },
  { topic: "fetch وطلبات الشبكة بعمق", kind: "lesson", level: "متوسط", focus: "رؤوس + JSON + معالجة الحالات + إلغاء", lang: JS, context: JS_CTX },
  { topic: "طرق المصفوفات المتقدمة", kind: "lesson", level: "متوسط", focus: "reduce/flatMap/some/every بأمثلة", lang: JS, context: JS_CTX },
  { topic: "Map وSet في جافاسكريبت", kind: "lesson", level: "متوسط", focus: "متى تفضّلها على الكائن/المصفوفة", lang: JS, context: JS_CTX },
  { topic: "المولدات generators في جافاسكريبت", kind: "lesson", level: "متقدم", focus: "function* + yield + التكرار الكسول", lang: JS, context: JS_CTX },
  { topic: "التفكيك destructuring والنشر spread", kind: "lesson", level: "متوسط", focus: "فك الكائنات/المصفوفات + rest + نسخ", lang: JS, context: JS_CTX },
  { topic: "الكلمة this والربط bind/call/apply", kind: "lesson", level: "متقدم", focus: "قيمة this في الحالات + الربط الصريح", lang: JS, context: JS_CTX },
  { topic: "أحداث DOM بعمق", kind: "lesson", level: "متوسط", focus: "الالتقاط/الفقاعة + التفويض + preventDefault", lang: JS, context: "متصفح" },
  { topic: "المؤقتات وrequestAnimationFrame", kind: "lesson", level: "متوسط", focus: "setTimeout/Interval + rAF للحركة", lang: JS, context: "متصفح" },
  { topic: "الوعود المتوازية Promise.all وrace", kind: "lesson", level: "متوسط", focus: "all/race/allSettled/any واستخداماتها", lang: JS, context: JS_CTX },
  { topic: "Proxy وReflect في جافاسكريبت", kind: "lesson", level: "متقدم", focus: "اعتراض العمليات على الكائنات", lang: JS, context: JS_CTX },
  { topic: "WeakMap وWeakSet", kind: "lesson", level: "متقدم", focus: "مراجع ضعيفة + منع تسرب الذاكرة", lang: JS, context: JS_CTX },
  { topic: "الرموز Symbol واستخداماتها", kind: "lesson", level: "متقدم", focus: "مفاتيح فريدة + رموز معروفة", lang: JS, context: JS_CTX },
  { topic: "التواريخ Date وIntl في جافاسكريبت", kind: "lesson", level: "متوسط", focus: "التنسيق + المناطق + الفروق", lang: JS, context: JS_CTX },
  { topic: "أنماط التصميم في جافاسكريبت", kind: "lesson", level: "متقدم", focus: "Module/Observer/Factory بأمثلة", lang: JS, context: JS_CTX },
  { topic: "الأنواع المتقدمة generics في TypeScript", kind: "lesson", level: "متقدم", focus: "دوال وأصناف عامة + قيود extends", lang: TS, context: TS_CTX },
  { topic: "الأنواع المساعدة utility types", kind: "lesson", level: "متقدم", focus: "Partial/Pick/Omit/Record بأمثلة", lang: TS, context: TS_CTX },
  { topic: "interfaces مقابل types في TypeScript", kind: "lesson", level: "متوسط", focus: "الفروق + متى تستخدم كلاً منهما", lang: TS, context: TS_CTX },
  { topic: "الاتحادات unions وenums في TypeScript", kind: "lesson", level: "متوسط", focus: "أنواع موحّدة + literal types", lang: TS, context: TS_CTX },
  { topic: "تضييق النوع narrowing وtype guards", kind: "lesson", level: "متقدم", focus: "typeof/in/instanceof + دوال حارسة", lang: TS, context: TS_CTX },
  { topic: "مشروع REST API مع Express", kind: "system", level: "متقدم", focus: "مسارات + JSON + معالج أخطاء", lang: JS, context: "Node.js مع Express" },
  { topic: "مشروع دردشة WebSocket", kind: "system", level: "متقدم", focus: "اتصال حي + بث رسائل + انقطاع", lang: JS, context: "Node.js مع ws" },
  { topic: "مشروع تحقق نماذج form validation", kind: "system", level: "متوسط", focus: "قواعد + رسائل خطأ + منع الإرسال", lang: JS, context: "متصفح" },
  { topic: "مشروع لعبة ثعبان بالكانفس", kind: "system", level: "متوسط", focus: "شبكة + حركة + نمو + اصطدام", lang: JS, context: "متصفح + Canvas" },
  { topic: "مشروع محرر ملاحظات بالتخزين المحلي", kind: "system", level: "متوسط", focus: "إضافة/حذف + حفظ localStorage", lang: JS, context: "متصفح" },
  { topic: "مشروع جالب بيانات API وعرضها", kind: "system", level: "متوسط", focus: "fetch + حالة تحميل + عرض قائمة", lang: JS, context: "متصفح" },
  { topic: "مشروع أداة سطر أوامر Node", kind: "system", level: "متوسط", focus: "قراءة وسائط + عمليات ملفات + إخراج", lang: JS, context: "Node.js" },
  { topic: "الأداء وتحسين حلقات جافاسكريبت", kind: "lesson", level: "متقدم", focus: "تجنب إعادة الحساب + تقليل DOM reflow", lang: JS, context: JS_CTX },
  { topic: "الدوال المولّدة غير المتزامنة", kind: "lesson", level: "متقدم", focus: "async generators + for await...of", lang: JS, context: JS_CTX },
  { topic: "ESM مقابل CommonJS", kind: "lesson", level: "متوسط", focus: "import مقابل require + التوافق", lang: JS, context: "Node.js" },
  { topic: "التعامل مع الأخطاء غير المتزامنة", kind: "lesson", level: "متوسط", focus: "أخطاء الوعود + unhandledRejection", lang: JS, context: JS_CTX },
  { topic: "معالجة النصوص وregex في جافاسكريبت", kind: "lesson", level: "متوسط", focus: "match/replace/replaceAll + مجموعات", lang: JS, context: JS_CTX },
  { topic: "تنسيق الأرقام والعملات Intl.NumberFormat", kind: "lesson", level: "مبتدئ", focus: "عرض عملات ونِسب حسب اللغة", lang: JS, context: JS_CTX },
  { topic: "مشروع لوحة تحكم بيانات بسيطة", kind: "system", level: "متوسط", focus: "جلب + رسم بطاقات + تحديث دوري", lang: JS, context: "متصفح" },
  { topic: "أساسيات Node.js: fs وpath وprocess", kind: "lesson", level: "متوسط", focus: "قراءة/كتابة ملفات + مسارات + بيئة", lang: JS, context: "Node.js" },
];

/* ═══════════════════════ C++ — تعمّق ومشاريع ═══════════════════════ */
const CPP_EXT: AITopic[] = [
  { topic: "القوالب templates في C++", kind: "lesson", level: "متقدم", focus: "دوال وأصناف عامة + استنتاج النوع", lang: CPP, context: CPP_CTX },
  { topic: "خوارزميات المكتبة القياسية STL", kind: "lesson", level: "متوسط", focus: "sort/find/accumulate/transform", lang: CPP, context: CPP_CTX },
  { topic: "تعبيرات lambda في C++", kind: "lesson", level: "متوسط", focus: "الالتقاط + الاستخدام مع STL", lang: CPP, context: CPP_CTX },
  { topic: "دلالات النقل move semantics", kind: "lesson", level: "متقدم", focus: "std::move + rvalue + تجنب النسخ", lang: CPP, context: CPP_CTX },
  { topic: "مبدأ RAII في C++", kind: "lesson", level: "متقدم", focus: "إدارة الموارد عبر البناء/الهدم", lang: CPP, context: CPP_CTX },
  { topic: "زيادة تحميل المعاملات operator overloading", kind: "lesson", level: "متقدم", focus: "+/==/<< لأصناف مخصصة", lang: CPP, context: CPP_CTX },
  { topic: "الخيوط threads وmutex في C++", kind: "lesson", level: "متقدم", focus: "std::thread + lock_guard + سباقات", lang: CPP, context: CPP_CTX },
  { topic: "المؤشرات الذكية بعمق", kind: "lesson", level: "متقدم", focus: "unique/shared/weak_ptr ودورات المراجع", lang: CPP, context: CPP_CTX },
  { topic: "القوالب المتغيرة variadic templates", kind: "lesson", level: "متقدم", focus: "عدد وسائط متغير + التوسيع", lang: CPP, context: CPP_CTX },
  { topic: "constexpr والحساب وقت الترجمة", kind: "lesson", level: "متقدم", focus: "ثوابت وحسابات تُنفّذ عند الترجمة", lang: CPP, context: CPP_CTX },
  { topic: "namespaces وتنظيم الأسماء", kind: "lesson", level: "متوسط", focus: "منع التصادم + using بحذر", lang: CPP, context: CPP_CTX },
  { topic: "enum class والأنواع المحكمة", kind: "lesson", level: "متوسط", focus: "أنواع تعداد آمنة النطاق", lang: CPP, context: CPP_CTX },
  { topic: "std::vector بعمق والحجز reserve", kind: "lesson", level: "متوسط", focus: "النمو + reserve + تجنب النسخ", lang: CPP, context: CPP_CTX },
  { topic: "std::map وunordered_map", kind: "lesson", level: "متوسط", focus: "مرتّب مقابل تجزئة + الأداء", lang: CPP, context: CPP_CTX },
  { topic: "std::set وstd::unordered_set", kind: "lesson", level: "متوسط", focus: "عناصر فريدة + البحث السريع", lang: CPP, context: CPP_CTX },
  { topic: "std::optional وstd::variant", kind: "lesson", level: "متقدم", focus: "قيمة اختيارية + نوع من عدة أنواع", lang: CPP, context: CPP_CTX },
  { topic: "std::function والاستدعاء القابل", kind: "lesson", level: "متقدم", focus: "تخزين دوال/لامبدا + callbacks", lang: CPP, context: CPP_CTX },
  { topic: "المكرِّرات iterators في STL", kind: "lesson", level: "متوسط", focus: "begin/end + أنواع المكررات", lang: CPP, context: CPP_CTX },
  { topic: "الفرز والبحث في STL", kind: "lesson", level: "متوسط", focus: "std::sort بمقارن + binary_search", lang: CPP, context: CPP_CTX },
  { topic: "إدارة الذاكرة new/delete بأمان", kind: "lesson", level: "متقدم", focus: "متى تتجنبها لصالح المؤشرات الذكية", lang: CPP, context: CPP_CTX },
  { topic: "المراجع rvalue وlvalue", kind: "lesson", level: "متقدم", focus: "الفرق + && + المراجع العالمية", lang: CPP, context: CPP_CTX },
  { topic: "الوراثة الافتراضية وvirtual بعمق", kind: "lesson", level: "متقدم", focus: "الدوال الافتراضية + الهدّام الافتراضي", lang: CPP, context: CPP_CTX },
  { topic: "تخصيص القوالب template specialization", kind: "lesson", level: "متقدم", focus: "تخصيص كامل/جزئي بأمثلة", lang: CPP, context: CPP_CTX },
  { topic: "معالجة الاستثناءات بعمق في C++", kind: "lesson", level: "متقدم", focus: "throw/catch + الأمان الاستثنائي + RAII", lang: CPP, context: CPP_CTX },
  { topic: "مشروع محلل تعبيرات حسابية C++", kind: "system", level: "متقدم", focus: "تحليل + أولوية عمليات + تقييم", lang: CPP, context: CPP_CTX },
  { topic: "مشروع قائمة مترابطة C++", kind: "system", level: "متوسط", focus: "عقد + إدراج/حذف + مؤشرات ذكية", lang: CPP, context: CPP_CTX },
  { topic: "مشروع شجرة بحث ثنائية C++", kind: "system", level: "متقدم", focus: "إدراج/بحث/اجتياز", lang: CPP, context: CPP_CTX },
  { topic: "مشروع محاكاة طابور بنك C++", kind: "system", level: "متوسط", focus: "queue + خدمة عملاء + إحصاء", lang: CPP, context: CPP_CTX },
  { topic: "مشروع لعبة حياة Conway C++", kind: "system", level: "متقدم", focus: "شبكة + قواعد + أجيال", lang: CPP, context: CPP_CTX },
  { topic: "الإدخال والإخراج المتقدم iostream", kind: "lesson", level: "متوسط", focus: "التنسيق + stringstream + قراءة سطور", lang: CPP, context: CPP_CTX },
];

/* ═══════════════════════ أساسيات علوم الحاسب (لغة-محايدة، أمثلة لواو) ═══════════════════════ */
const CS_FUNDAMENTALS: AITopic[] = [
  // هياكل بيانات
  { topic: "القوائم المترابطة linked list", kind: "lesson", level: "متوسط", focus: "عقدة + مؤشر تالٍ + إدراج/حذف + متى تفيد" },
  { topic: "القائمة المترابطة المزدوجة", kind: "lesson", level: "متوسط", focus: "مؤشران + تنقل باتجاهين + مقارنة بالمفردة" },
  { topic: "المكدس stack وتطبيقاته", kind: "lesson", level: "متوسط", focus: "LIFO + push/pop + تطبيق التراجع والأقواس" },
  { topic: "الطابور queue وتطبيقاته", kind: "lesson", level: "متوسط", focus: "FIFO + enqueue/dequeue + طابور المهام" },
  { topic: "الطابور ذو الأولوية priority queue", kind: "lesson", level: "متقدم", focus: "ترتيب حسب أولوية + استخدام الكومة" },
  { topic: "جدول التجزئة hash table", kind: "lesson", level: "متقدم", focus: "دالة تجزئة + التصادمات + O(1) متوسط" },
  { topic: "الشجرة tree ومصطلحاتها", kind: "lesson", level: "متوسط", focus: "جذر/ورقة/عمق/ارتفاع + تمثيل" },
  { topic: "شجرة البحث الثنائية BST", kind: "lesson", level: "متقدم", focus: "خاصية الترتيب + إدراج/بحث + التدهور" },
  { topic: "الشجرة المتوازنة AVL", kind: "lesson", level: "متقدم", focus: "التوازن + الدوران + ضمان O(log n)" },
  { topic: "الكومة heap الثنائية", kind: "lesson", level: "متقدم", focus: "min/max heap + heapify + الاستخدامات" },
  { topic: "الرسم البياني graph وتمثيله", kind: "lesson", level: "متقدم", focus: "قائمة/مصفوفة جوار + موجّه/غير موجّه" },
  { topic: "الشجرة الثلاثية trie", kind: "lesson", level: "متقدم", focus: "تخزين كلمات + بحث بادئة + إكمال تلقائي" },
  { topic: "المصفوفة الديناميكية dynamic array", kind: "lesson", level: "متوسط", focus: "التوسيع المضاعف + التكلفة المطفأة" },
  { topic: "المصفوفات متعددة الأبعاد", kind: "lesson", level: "متوسط", focus: "الشبكات + الفهرسة + استخدامات الألعاب" },
  { topic: "بنية الاتحاد والبحث union-find", kind: "lesson", level: "متقدم", focus: "الاتحاد بالرتبة + ضغط المسار" },
  // خوارزميات
  { topic: "تحليل التعقيد Big-O", kind: "lesson", level: "متوسط", focus: "الزمن والمكان + O(1)/O(n)/O(log n)/O(n²)" },
  { topic: "الفرز الفقاعي bubble sort", kind: "lesson", level: "مبتدئ", focus: "الفكرة + التنفيذ + لماذا بطيء O(n²)" },
  { topic: "فرز الإدراج insertion sort", kind: "lesson", level: "مبتدئ", focus: "بناء مرتّب تدريجياً + متى يكون جيداً" },
  { topic: "فرز الاختيار selection sort", kind: "lesson", level: "مبتدئ", focus: "اختيار الأصغر كل مرة + التحليل" },
  { topic: "الفرز السريع quicksort", kind: "lesson", level: "متقدم", focus: "المحور + التقسيم + متوسط O(n log n)" },
  { topic: "الفرز بالدمج merge sort", kind: "lesson", level: "متقدم", focus: "التقسيم + الدمج + الاستقرار O(n log n)" },
  { topic: "فرز الكومة heap sort", kind: "lesson", level: "متقدم", focus: "بناء كومة + استخراج متكرر" },
  { topic: "البحث الخطي والثنائي", kind: "lesson", level: "متوسط", focus: "linear مقابل binary + شرط الترتيب" },
  { topic: "البحث بالعرض BFS", kind: "lesson", level: "متقدم", focus: "طابور + مستوى بمستوى + أقصر مسار غير موزون" },
  { topic: "البحث بالعمق DFS", kind: "lesson", level: "متقدم", focus: "مكدس/عودية + اجتياز كامل + التطبيقات" },
  { topic: "خوارزمية Dijkstra لأقصر مسار", kind: "lesson", level: "متقدم", focus: "أوزان موجبة + طابور أولوية" },
  { topic: "خوارزمية A* للمسارات", kind: "lesson", level: "متقدم", focus: "heuristic + مقارنة بـ Dijkstra" },
  { topic: "مقدمة البرمجة الديناميكية DP", kind: "lesson", level: "متقدم", focus: "مسائل متداخلة + بناء من الأسفل" },
  { topic: "مشكلة الحقيبة knapsack", kind: "lesson", level: "متقدم", focus: "0/1 + جدول DP + التتبع" },
  { topic: "أطول متتالية جزئية مشتركة LCS", kind: "lesson", level: "متقدم", focus: "جدول DP + استعادة الحل" },
  { topic: "الخوارزميات الجشعة greedy", kind: "lesson", level: "متوسط", focus: "الاختيار المحلي الأمثل + متى تنجح" },
  { topic: "التراجع backtracking", kind: "lesson", level: "متقدم", focus: "استكشاف + تراجع + مثال الملكات" },
  { topic: "العودية recursion وأساسياتها", kind: "lesson", level: "متوسط", focus: "الحالة الأساس + الثقة بالعودية + المكدس" },
  { topic: "حل وسيطر divide and conquer", kind: "lesson", level: "متقدم", focus: "تقسيم + حل + دمج بأمثلة" },
  { topic: "تقنية المؤشرين two pointers", kind: "lesson", level: "متوسط", focus: "مصفوفة مرتّبة + مجموع هدف" },
  { topic: "النافذة المنزلقة sliding window", kind: "lesson", level: "متقدم", focus: "نطاق متحرك + أفضل من التكرار المزدوج" },
  { topic: "الحفظ memoization", kind: "lesson", level: "متوسط", focus: "تخزين النتائج + تسريع العودية" },
  { topic: "مطابقة النصوص string matching", kind: "lesson", level: "متقدم", focus: "البحث الساذج + فكرة KMP" },
  { topic: "أعداد فيبوناتشي بطرق متعددة", kind: "lesson", level: "متوسط", focus: "عودية/تكرار/DP ومقارنة الأداء" },
  { topic: "الأعداد الأولية وغربال إراتوستينس", kind: "lesson", level: "متوسط", focus: "فحص أولية + الغربال الفعّال" },
  // مفاهيم
  { topic: "المصفوفة مقابل القائمة المترابطة", kind: "lesson", level: "متوسط", focus: "الوصول العشوائي مقابل الإدراج + متى تختار" },
  { topic: "اختيار هيكل البيانات المناسب", kind: "lesson", level: "متوسط", focus: "ربط العملية المطلوبة بأفضل هيكل" },
  { topic: "الاستقرار في خوارزميات الفرز", kind: "lesson", level: "متوسط", focus: "ما معناه ولماذا يهم أحياناً" },
  { topic: "التعقيد المكاني مقابل الزمني", kind: "lesson", level: "متوسط", focus: "المفاضلة + أمثلة عملية" },
  { topic: "اجتياز الأشجار inorder وpreorder", kind: "lesson", level: "متقدم", focus: "الأنواع الثلاثة + متى يستخدم كلٌّ" },
  { topic: "الطوابير والمكدسات في حل المشكلات", kind: "lesson", level: "متوسط", focus: "أمثلة أقواس متوازنة وطابور مهام" },
  { topic: "كشف الدورات في الرسوم البيانية", kind: "lesson", level: "متقدم", focus: "DFS + حالات الزيارة" },
  { topic: "تمثيل الرسم البياني عملياً", kind: "lesson", level: "متقدم", focus: "قائمة الجوار مقابل مصفوفة الجوار" },
  { topic: "الأشجار في تنظيم البيانات الواقعية", kind: "lesson", level: "متوسط", focus: "ملفات/قوائم/مشاهد لعبة كأشجار" },
  { topic: "مقدمة في التجزئة العملية", kind: "lesson", level: "متوسط", focus: "خرائط سريعة + تجنب التصادم الفعلي" },
];

/* ═══════════════════════ مهارات وأدوات المبرمج ═══════════════════════ */
const CRAFT_EXT: AITopic[] = [
  { topic: "أساسيات git للمبرمج المبتدئ", kind: "lesson", level: "مبتدئ", focus: "init/add/commit/status/log بأمثلة", context: "طرفية مع git" },
  { topic: "فروع git والدمج merge", kind: "lesson", level: "متوسط", focus: "branch/checkout/merge + متى تفرّع", context: "طرفية مع git" },
  { topic: "حل تعارضات git conflicts", kind: "lesson", level: "متوسط", focus: "قراءة علامات التعارض + الحل اليدوي", context: "طرفية مع git" },
  { topic: "كتابة رسائل commit جيدة", kind: "lesson", level: "مبتدئ", focus: "رسالة واضحة موجزة + لماذا لا ماذا فقط", context: "طرفية مع git" },
  { topic: "أساسيات GitHub والتعاون", kind: "lesson", level: "متوسط", focus: "push/pull + Pull Request + المراجعة", context: "GitHub" },
  { topic: "كتابة اختبارات الوحدة unit tests", kind: "lesson", level: "متوسط", focus: "ماذا نختبر + ترتيب/تنفيذ/تحقق" },
  { topic: "التطوير الموجّه بالاختبار TDD", kind: "lesson", level: "متقدم", focus: "أحمر-أخضر-إعادة هيكلة بمثال" },
  { topic: "مبادئ الكود النظيف clean code", kind: "lesson", level: "متوسط", focus: "أسماء واضحة + دوال صغيرة + تجنب التعقيد" },
  { topic: "مبادئ SOLID للتصميم", kind: "lesson", level: "متقدم", focus: "المبادئ الخمسة مبسّطة بأمثلة" },
  { topic: "مراجعة الكود code review الفعّالة", kind: "lesson", level: "متوسط", focus: "ماذا نبحث عنه + نبرة بنّاءة" },
  { topic: "قراءة التوثيق الرسمي بفعالية", kind: "lesson", level: "مبتدئ", focus: "كيف تجد الدالة وتفهم توقيعها وأمثلتها" },
  { topic: "البحث عن حلول الأخطاء بذكاء", kind: "lesson", level: "مبتدئ", focus: "صياغة السؤال + قراءة رسالة الخطأ + المصادر" },
  { topic: "وضع خطة تعلم برمجية", kind: "lesson", level: "مبتدئ", focus: "أهداف + مشاريع صغيرة + تكرار يومي" },
  { topic: "إدارة مشروع برمجي صغير", kind: "lesson", level: "متوسط", focus: "تقسيم المهام + أولويات + تتبع" },
  { topic: "أنماط التصميم design patterns مقدمة", kind: "lesson", level: "متقدم", focus: "Singleton/Observer/Factory متى ولماذا" },
  { topic: "مبدأ DRY وتجنب التكرار", kind: "lesson", level: "متوسط", focus: "استخراج المشترك + مخاطر التجريد المبكر" },
  { topic: "مبدأ KISS والبساطة", kind: "lesson", level: "مبتدئ", focus: "أبسط حل يعمل + تجنب الهندسة الزائدة" },
  { topic: "تقدير الوقت وتقسيم المهام", kind: "lesson", level: "متوسط", focus: "تجزئة + هامش أمان + قياس فعلي" },
  { topic: "بناء معرض أعمال portfolio للمبرمج", kind: "lesson", level: "مبتدئ", focus: "مشاريع تُظهر مهارة + وصف واضح" },
  { topic: "التعامل مع الكود القديم legacy", kind: "lesson", level: "متقدم", focus: "الفهم قبل التغيير + تغييرات صغيرة آمنة" },
];

/** كل مواضيع المنهج الموسّع مدموجة (تُدرَّب بعد المنهج الأساسي، بالخلفية). */
export const EXTENDED_TOPICS: AITopic[] = [
  ...ROBLOX_DEEP,
  ...ROBLOX_SYSTEMS,
  ...PYTHON_EXT,
  ...JS_EXT,
  ...CPP_EXT,
  ...CS_FUNDAMENTALS,
  ...CRAFT_EXT,
];
